name: 回测 SPY 0620 和 0623

on:
  workflow_dispatch:
  push:
    paths:
      - 'spy_backtest_date.py'
      - 'requirements.txt'
      - '.github/workflows/backtest_0620_0623.yml'

jobs:
  backtest:
    runs-on: ubuntu-latest

    steps:
      - name: 设置 Python 版本（改为 3.10）
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: 执行回测脚本
        run: python spy_backtest_date.py






