name: Troubleshoot SPY Backtest

on:
  workflow_dispatch:
  push:
    paths:
      - 'spy_backtest_date.py'
      - 'requirements.txt'
      - 'run_backtest.py'
      - '.github/workflows/backtest_troubleshoot.yml'

jobs:
  troubleshoot:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 设置 Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 运行 Troubleshoot 回测
        run: python run_backtest.py


