name: Test NASDAQ Backfill Dates

on:
  workflow_dispatch:

jobs:
  test-backfill:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas pandas_market_calendars 

      - name: Run backfill test script
        run: python test_backfill.py
