name: Backtest and Analyze

on:
  workflow_dispatch:
  schedule:
    - cron: '30 21 * * *'  # 每天美股收盘后（21:30 EST）运行

jobs:
  run-backtest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install pandas yfinance pandas_ta

      - name: Run Backtest
        run: python spy_backtest_20250626.py

      - name: Run Analyzer
        run: python strategy_refinement_analyzer_backtest.py
