name: Run SPY Backtest

on:
  workflow_dispatch:  # 手动触发

jobs:
  backtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run backtest script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: python spy_backtest_LTD.py

      - name: Upload backtest result CSV
        uses: actions/upload-artifact@v4
        with:
          name: backtest-signals
          path: signal_log_backtest.csv
