name: 检查可用包版本

on:
  workflow_dispatch:

jobs:
  check_versions:
    runs-on: ubuntu-latest

    steps:
      - name: 设置 Python 版本
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 检出代码
        uses: actions/checkout@v3

      - name: 升级 pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: 安装 pip 的索引工具
        run: python -m pip install --upgrade pip  # 保证 pip 新版本

      - name: 运行版本检测脚本
        run: python check_versions.py
