name: Backtest SPY with Debug

on:
  workflow_dispatch:

jobs:
  run-backtest:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install numpy==1.23.5
          pip install pandas>=1.3
          pip install pandas_market_calendars
          pip install pandas_ta==0.3.14b0
          pip install yfinance
          pip install requests

      - name: Run backtest with debug
        run: python backtest_with_debug.py
