name: Run SPY Signal Every Minute

on:
  schedule:
    # UTC时间，每分钟运行一次
    - cron: "*/1 * * * *"
  workflow_dispatch:  # 允许手动触发

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install yfinance pandas pandas_ta requests

    - name: Run script
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: |
        python spy_signal_bot_v4.py
