name: Run SPY Signal Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # 每分钟执行一次
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.14 beta
        uses: actions/setup-python@v4
        with:
          python-version: 3.14.0-beta.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the signal script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: python spy_signal_bot_v4.py
