name: Run SPY Signal Every Minute

on:
  schedule:
    - cron: '*/1 * * * *'  # 每分钟执行一次
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install numpy==1.23.5
          pip install yfinance pandas pandas_ta requests

      - name: Run the signal script
        run: python spy_signal_bot_v4.py
