name: Test Discord Webhook

on:
  workflow_dispatch:

jobs:
  test-webhook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install requests
        run: pip install requests

      - name: Run test script
        run: python test_discord.py
